export type PenObject = {
  id: string;
  label: string;
  // Top-left position in grid cells. Everything else is derived from
  // width / length / rotation.
  col: number;
  row: number;
  width: number; // size across, in cells
  length: number; // size down, in cells
  rotation: number; // degrees, clockwise, pivoting on the top-left corner
  shape?: 'rect' | 'triangle' | 'circle'; // defaults to 'rect'
};

export const penObjects: PenObject[] = [
  {
    label: '🏠 Left Townhouse',
    id: 'house-1',
    col: 19,
    row: 8,
    width: 3,
    length: 3,
    rotation: 90,
  },
  {
    label: '🏠 Right Townhouse',
    id: 'house-2',
    col: 3,
    row: 5,
    width: 3,
    length: 3,
    rotation: 0,
  },
  {
    label: '🏠 Townhouse Extension Left',
    id: 'townhouse-extension-left',
    col: 19,
    row: 12,
    width: 3,
    length: 3,
    rotation: 90,
  },
  {
    label: '🏠 House with Porch',
    id: 'house-with-porch',
    col: 10,
    row: 5,
    width: 3,
    length: 3,
    rotation: 0,
  },
  {
    label: '🏚️ Tiny House 2',
    id: 'tiny-house-2',
    col: 7,
    row: 4,
    width: 2,
    length: 1,
    rotation: 0,
  },
  {
    label: '💧 Water Station',
    id: 'water-station',
    col: 0,
    row: 10,
    width: 2,
    length: 5,
    rotation: 0,
  },
  {
    label: '🍽️ Table',
    id: 'table',
    col: 4,
    row: 11,
    width: 2,
    length: 3,
    rotation: 0,
  },
  {
    label: '⛺ A-Frame',
    id: 'aframe',
    col: 0,
    row: 4,
    width: 4,
    length: 2,
    rotation: -90,
  },
  {
    label: '🛖 Barn',
    id: 'barn',
    col: 19,
    row: 15,
    width: 3,
    length: 2,
    rotation: 90,
  },
  {
    label: '🏚️ Tiny House',
    id: 'tiny-house',
    col: 19,
    row: 18,
    width: 2,
    length: 1,
    rotation: 90,
  },
  {
    label: '🌉 Bridge',
    id: 'bridge',
    col: 4,
    row: 18,
    width: 4,
    length: 1,
    rotation: 40,
  },
  {
    label: '🌳 Tree',
    id: 'tree',
    col: 1,
    row: 19,
    width: 3,
    length: 3,
    rotation: 0,
    shape: 'circle',
  },
  {
    label: '🥣 Kibble Station',
    id: 'kibble-station',
    col: 8,
    row: 19,
    width: 2,
    length: 2,
    rotation: 0,
    shape: 'circle',
  },
  {
    label: '🏖️ Cabana',
    id: 'cabana',
    col: 15,
    row: 4,
    width: 4,
    length: 4,
    rotation: 0,
  },
  {
    label: '🏖️ Barbie Dream House',
    id: 'barbie-dream-house',
    col: 13,
    row: 6,
    width: 2,
    length: 2,
    rotation: 0,
  },
  {
    label: '🤖 R2D2',
    id: 'r2d2',
    col: 12,
    row: 16,
    width: 1,
    length: 1,
    rotation: 0,
  },
  {
    label: '🏟️ Long House',
    id: 'long-house',
    col: 7,
    row: 15,
    width: 6,
    length: 3,
    rotation: -45,
  },
  {
    label: '⛺ Tiny House 3',
    id: 'tiny-house-3',
    col: 0,
    row: 21,
    width: 2,
    length: 2,
    rotation: 0,
    shape: 'triangle',
  },
];
